version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    environment:
      POLYGON_SECRET:
      OER_SECRET:
    build: ./backend/
    ports:
      - "6200:6200"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./frontend/
    ports:
      # Prod port
      # - "5000:5000"
      # Dev port
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
